### ISSUE TITLE
note: rust-lld: error: unable to find library -lcmsis_rtos2

### ISSUE THREAD

**Issue by rise0chen** [tstellanova/rolkien#1]

**Comment by rise0chen** [comment]
![image](https://user-images.githubusercontent.com/12853908/86554972-a9485e00-bf81-11ea-94c0-7e459bbe1493.png)

**Comment by tstellanova** [comment]
@rise0chen Can you provide more info on how you're running this build? 
It appears you're using nightly instead of stable?

I just now pulled the latest code and ran "cargo build" without incident.

**Comment by rise0chen** [comment]
@tstellanova 
Both `stable-x86_64-pc-windows-msvc` and `nightly-x86_64-pc-windows-msvc` can show this error when I run `cargo build`.
And, `make` cmd from `cygwin`.

**Comment by tstellanova** [comment]
Ok I guess this is an issue with the cygwin environment. I’ve run simply `cargo build` on both linux (ubuntu LTS) and Mac OSX.
